
hero_image: assets/img/hero_shot.jpg
hero_position: center center
# mobile_hero_image: assets/img/bell.jpg
# mobile_hero_position: center center

theme:
  # text_color: '#404040'
  primary_color: '#769ed6'
  secondary_color: '#769ed6'
  # accent_color: '#afa63d'
  # background_color: '#ffff'
